name: TWRP Minimal Builder

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: "MANIFEST_URL"
        required: true
        default: "https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp"
      MANIFEST_BRANCH:
        description: "MANIFEST_BRANCH"
        required: true
        default: "twrp-12.1"
      DEVICE_TREE_URL:
        description: "DEVICE_TREE_URL"
        required: true
        default: "https://github.com/TeamWin/android_device_samsung_a23xq"
      DEVICE_TREE_BRANCH:
        description: "DEVICE_TREE_BRANCH"
        required: true
        default: "android-12.1"
      DEVICE_PATH:
        description: "DEVICE_PATH"
        required: true
        default: "device/samsung/a23xq"
      DEVICE_CODENAME:
        description: "DEVICE_CODENAME"
        required: true
        default: "a23xq"
      MAKEFILE_NAME:
        description: "MAKEFILE_NAME"
        required: true
        default: "twrp_a23xq"
      PARTITION_TARGET:
        description: "PARTITION_TARGET"
        required: true
        default: "recovery"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display run parameters
        run: |
          echo "MANIFEST URL: ${{ github.event.inputs.MANIFEST_URL }}"
          echo "MANIFEST BRANCH: ${{ github.event.inputs.MANIFEST_BRANCH }}"
          echo "DEVICE TREE URL: ${{ github.event.inputs.DEVICE_TREE_URL }}"
          echo "DEVICE TREE BRANCH: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}"
          echo "DEVICE PATH: ${{ github.event.inputs.DEVICE_PATH }}"
          echo "DEVICE CODENAME: ${{ github.event.inputs.DEVICE_CODENAME }}"
          echo "MAKEFILE NAME: ${{ github.event.inputs.MAKEFILE_NAME }}"
          echo "PARTITION TARGET: ${{ github.event.inputs.PARTITION_TARGET }}.img"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install git-core gnupg flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig
          sudo mkdir -p /mnt/workspace
          sudo chown $USER:$USER /mnt/workspace

      - name: Install repo
        run: |
          mkdir -p ~/.bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          chmod a+rx ~/.bin/repo
          sudo ln -s ~/.bin/repo /usr/bin/repo

      - name: Cache
        uses: actions/cache@v4.2.0
        with:
          path: /mnt/workspace/.repo
          key: repo-${{ github.event.inputs.MANIFEST_BRANCH }}

      - name: Initialize repo
        run: |
          repo init --depth 1 -b ${{ github.event.inputs.MANIFEST_BRANCH }} -u ${{ github.event.inputs.MANIFEST_URL }}
        working-directory: /mnt/workspace

      - name: Sync repo
        run: |
          repo sync -j$(nproc --all)
        working-directory: /mnt/workspace

      - name: Clone device tree
        run: |
          git clone --depth 1 -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ${{ github.event.inputs.DEVICE_TREE_URL }} ${{ github.event.inputs.DEVICE_PATH }}
        working-directory: /mnt/workspace

      - name: Build recovery
        run: |
          source build/envsetup.sh
          lunch ${{ github.event.inputs.MAKEFILE_NAME }}-user
          make ${{ github.event.inputs.PARTITION_TARGET }}image -j$(nproc --all)
        working-directory: /mnt/workspace

      - name: GH Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: |
            /mnt/workspace/out/target/product/${{ github.event.inputs.DEVICE_CODENAME }}/${{ github.event.inputs.PARTITION_TARGET }}.img
          name: ${{ github.event.inputs.DEVICE_CODENAME }}-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: |
            MANIFEST URL: ${{ github.event.inputs.MANIFEST_URL }}
            MANIFEST BRANCH: ${{ github.event.inputs.MANIFEST_BRANCH }}
            DEVICE TREE URL: ${{ github.event.inputs.DEVICE_TREE_URL }}
            DEVICE TREE BRANCH: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}
            DEVICE PATH: ${{ github.event.inputs.DEVICE_PATH }}
            DEVICE CODENAME: ${{ github.event.inputs.DEVICE_CODENAME }}
            MAKEFILE NAME: ${{ github.event.inputs.MAKEFILE_NAME }}
            PARTITION TARGET: ${{ github.event.inputs.PARTITION_TARGET }}.img
